### ISSUE TITLE
Migrate Trail functionality to an API

### ISSUE THREAD

**Issue by timoguin** [tiki/core#11]
# Description

The core TIKI publish SDK is written in Dart and is embedded within our SDKs. This leads to complexity on the implementation side. To simplify things for the end user, we'd like to rewrite all this core logic in Rust and deploy it as a regular REST API.

# Issues

- [x] https://github.com/tiki/publish-license-upload/issues/134
- [x] https://github.com/tiki/publish-license-upload/issues/130
- [x] https://github.com/tiki/publish-license-upload/issues/136
- [x] https://github.com/tiki/publish-license-upload/issues/131
- [x] https://github.com/tiki/core-account-service/issues/329
- [x] https://github.com/tiki/publish-license-upload/issues/137
- [x] https://github.com/tiki/publish-license-upload/issues/135
- [x] https://github.com/tiki/publish-license-upload/issues/133
- [x] https://github.com/tiki/publish-license-upload/issues/132
- [x] https://github.com/tiki/publish-license-upload/issues/129
- [x] https://github.com/tiki/publish-license-upload/issues/62
- [x] https://github.com/tiki/publish-license-upload/issues/61
- [x] https://github.com/tiki/publish-license-upload/issues/138
- [x] https://github.com/tiki/publish-license-upload/issues/139
- [x] https://github.com/tiki/publish-license-upload/issues/140
- [x] https://github.com/tiki/publish-license-upload/issues/141 

- [x] tiki/core-trail-endpoint/issues/330
- [x] tiki/core-trail-endpoint/issues/331
- [x] tiki/core-trail-endpoint/issues/332
- [x] tiki/core-trail-endpoint/issues/333
- [x] tiki/core-trail-endpoint/issues/334
- [x] tiki/core-trail-endpoint/issues/335

**Comment by mike-audi** [comment]
The following issues need to be resolved to close this out.

- Move the transaction signing code to the endpoint - required to create the asset ref between titles and licenses
- Update the SQS payload for transactions being compiled in the endpoint
- Rust pattern for transactions having multiple schemas - use serde with custom serialization for generics
- Move the transactions outside of the block slice
